name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.5']
        appraisal-version: ['rails-5-0', 'rails-5-1', 'rails-5-2', 'rails-6']
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Setup appraisal
      run: |
        bundle exec appraisal install

    - name: Run all tests
      env:
        RAILS_ENV: test
      run: bundle exec appraisal ${{ matrix.appraisal-version }} rspec
