name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["2.5", "3.0"]
        gemfile: ["rails_5_0", "rails_5_1", "rails_5_2", "rails_6", "rails_7"]
        exclude:
          - ruby-version: "3.0"
            gemfile: "rails_5_0"
          - ruby-version: "3.0"
            gemfile: "rails_5_1"
          - ruby-version: "3.0"
            gemfile: "rails_5_2"
          - ruby-version: "2.5"
            gemfile: "rails_7"

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: default
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run all tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec
